apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: prod-team  
    namespace: argocd

spec:
  description: Development Application

  sourceRepos:
      - https://github.com/tusharyadav235/argocd-demo.git 
  destinations:
      - namespace: default
        server: https://kubernetes.default.svc 
  clusterResourceWhitelist:
     - group: "*"
       kind: "*"
  namespaceResourceWhitelist:
     - group: "*"
       kind: "*"
  roles:                       # Define roles for RBAC within this Project
    - name: prod-admins    # Role name  
      description: Admins for prod team
      policies:               
        - p, proj:prod-team:prod-admins, applications, *, prod-team/*, allow      

