apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: frontend-team  
    namespace: argocd

spec:
  description: Development Application

  sourceRepos:
      - https://github.com/tusharyadav235/argocd-demo.git 
  destinations:
      - namespace: frontend
        server: https://172.31.36.135:33893 
  clusterResourceWhitelist:
     - group: "*"
       kind: "*"
  namespaceResourceWhitelist:
     - group: "*"
       kind: "*"
  roles:                       # Define roles for RBAC within this Project
    - name: frontend-admins    # Role name  
      description: Admins for frontend team
      policies:               
        - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow      

